
#数据库连接配置
spring:
#  redis:
#    host: 192.168.111.129
#    port: 6379
  datasource:
    #用户名
    username: "root2"
    #密码
    password: "010607"
    # url需要指定时区serverTimezone为 GMT%2B8 ：北京时间东八区
    url: jdbc:mysql://localhost:3306/bishe?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    # 新版的驱动类改成了com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置druid数据库连接池时type这项必选
    type: com.alibaba.druid.pool.DruidDataSource
    #下面属性可选
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      use-global-data-source-stat: true
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  #配置thymeleaf渲染视图
  thymeleaf:
   # prefix: classpath:/templates/views/
    suffix: .html
    enabled: true
    cache: false  # 关闭缓存
    encoding: UTF-8
    servlet:
      content-type: text/html
  #修改json返回时间类型数据的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



mybatis-plus:
  mapper-locations:
  - classpath:Mapper/*Mapper.xml
#springboot+mybatis-plus 两种方式打印sql语句
#  configuration:
#        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:8
#    db-config:
#      id-type: auto
#    banner: true

# 分页配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

#  使用mybatis配置文件时需要指明
#mybatis:
#  #  config-location: classpath:mybatis/mybatis-config.xml
#  # 指定sql映射文件位置
#  mapper-locations:  classpath:com/bjpowernode/finance/mapper/*.xml


#shiro的配置
shiro:
  anon-urls:
  - /login/**
  - /resources/**
  - /bootstrap/**
  - /js/**
  - /lyear/**
  - /error/**
  - /register.html
  loginurl: /
  log-out-url: /login/logout*
  authc-ulrs:
  - /**
#  user-urls:
#  - /**


server:
  #端口设置
  port: 8080
  servlet:
    session:
      #session超时时间设置：2小时 7200秒
      timeout: PT2H
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} === [%thread] === %-5level %logger{50} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} --- [%thread] --- %-5level %logger{50} - %msg%n"
#  file:
#    path:
#    name: "D:/Test-biyesheji/log/logback.%d{yyyy-MM-dd}.%i.log"
#  level: #级别默认为info   TRACE < DEBUG < INFO < WARN < ERROR < FATA
#    root: info

logging:
  config: classpath:logback.xml